### ISSUE TITLE
Option 'z, cacheSpectraToDisk' does not evaluate as positive if present but not set to true

### ISSUE THREAD

**Issue by mwalzer** [PaulBrack/Yamato#128]
From `--help`, option z looks like a flag but using it like one yields
```
Singularity> SwaMe.Console -z -i split_napedro_L120420_010_SW-400AQUA__human_2ul_dilution_1_1.nf.pp.mzML  
SwaMe.Console 1.0.0
Copyright (C) 2020 SwaMe.Console

ERROR(S):
  Option 'z, cacheSpectraToDisk' has no value.
```
Am I supposed to set it to `true`? Seems that is working in so far as I get to the ouput described in #127

**Comment by marinaPauw** [comment]
Hello! Yes, the idea is to specify a bool after so: -z true or -z false.



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by PaulBrack** [comment]
@mwalzer agreed that the behaviour of this variable requiring an argument is confusing - this should default to false and evaluate to true on presence

**Comment by PaulBrack** [comment]
@mwalzer amended in 81f2a908936a1f346ef5a6e2d93b9f24198875b6
