### ISSUE TITLE
Respect the current directory at program run time for file paths

### ISSUE THREAD

**Issue by Ozzard** [PaulBrack/Yamato#135]
At present, running:
`SwaMe.Console -i ./aFile.wiff`
fails with a file not found exception even if the file exists in the current directory.  The backtrace indicates that the code is trying to find the file in a run-specific subdirectory; it would appear that the code changes directory before opening the input file, therefore requiring an absolute path (or a relative path from the subdirectory).

Expected behaviour: as essentially every other program since the MULTICS days, resolve all relative paths relative to the current directory at program launch.

**Comment by PaulBrack** [comment]
@Ozzard can you test please?

**Comment by Ozzard** [comment]
Appears to be working - many thanks!
