### ISSUE TITLE
When publishing standalone Linux binaries, publish the "publish" directory not the base directory

### ISSUE THREAD

**Issue by Ozzard** [PaulBrack/Yamato#137]
At present, the packaging of the standalone Linux distribution puts the standalone in a "publish" subdirectory, which is confusing as the parent contains similar binaries that are not runnable standalone.

Ideally, we would only publish the standalone rather than its parent directory, and we would modify the container creation scripts to handle this change.

Happy to tackle this if I can get permission to amend jobs on the repo.

**Comment by PaulBrack** [comment]
@Ozzard can you confirm this works as expected?

**Comment by Ozzard** [comment]
This is as expected; interestingly, everything's in a single executable.  Worth keeping the zip file in case we want to add docs and data files, I think.

**Comment by PaulBrack** [comment]
@Ozzard the single file was an active decision - see build switch -p:PublishSingleFile=true

Zip file is a neccessity - it's how the publish tool works
