### ISSUE TITLE
Ensure all metrics available from Yamato/SwaMe/Prognosticator are available in a single mzQC output file

### ISSUE THREAD

**Issue by Ozzard** [PaulBrack/Yamato#138]
At present, the console application always creates several files: one mzQC, and then other TSVs containing other metrics.  This is difficult to consume in any database-based QC pipeline, for example the one at the Stoller.  All of these metrics should be available in a single byte stream; given that mzQC is allegedly designed for this purpose, all of these metrics should be available in a mzQC byte stream, expressed as a file or via stdout (see also #100).

Note: I have no problem with these metrics being duplicated in other files, as long as there is a way of turning off the generation of anything except the mzQC file - perhaps --generateMzQCOnly?

See also #24 - it is interesting to note that the project has eschewed mzQC for the faster-moving experimental work.  I believe this issue shows a fundamental flaw with the processes around mzQC, as users are discouraged from creating their own vocabularies for new terms and instead have to go through a central allocation process.  I believe this will reduce the uptake of mzQC as it is insufficiently agile for real use cases.  I have commented informally to the working group; I should perhaps raise it formally.

**Comment by PaulBrack** [comment]
@marinaPauw can you confirm that all of your metrics are already available in the mzQC?

**Comment by PaulBrack** [comment]
Closing as all other file outputs removed
