### ISSUE TITLE
Allow the user to specify an output file path and name for at least the mzQC file, and ideally all files

### ISSUE THREAD

**Issue by Ozzard** [PaulBrack/Yamato#139]
At present, the program appears to site its output relative to the full path of its input.  This gives rise to multiple problems:
* The program tries to detect its current directory and change directories if that isn't the expected directory.  The detection fails badly on UNIX derivatives, where symbolic links are common, hard links are possible, and the program's canonical working directory is very likely not to be the same as the path the user passes in.
* Where the input is in a read-only section of filestore (as most input should be for production use), the program appears to try to write its output to the read-only location.
* The output path is not predictable, as it includes a date and time generated as the program runs.  Particularly for cluster systems where a job may run seconds to days after it is submitted, this non-determinism is highly undesirable.

The program should at least allow the specification of an output directory and write files into that with a known name.

Ideally, the program should allow the specification of a single output *file* name (not directory name) and write just the mzQC file (see #138) to that path.  See also #100 for writing to stdout instead.

**Comment by PaulBrack** [comment]
@Ozzard - I've discussed this with @marinaPauw and we're happy to strip out all the c/tsv output and provide a command line argument to specify the output file location, will this suit?

**Comment by Ozzard** [comment]
Ideal.

**Comment by PaulBrack** [comment]
@Ozzard this is ready to test, can you give it a spin please?

**Comment by Ozzard** [comment]
Working.
