### ISSUE TITLE
At present, this QC tool cannot provide faster QC indication for SCIEX 6600 files than can Skyline with a simple R or Ruby script

### ISSUE THREAD

**Issue by Ozzard** [PaulBrack/Yamato#144]
Due to this tool only ingesting the very verbose mzML format, real runtimes for QC are currently around 30 minutes on Linux.  This appears to be due to a comms bottleneck between the WIFF converter and this tool.

Skyline will ingest the same file in around 5 minutes, using somewhat lower CPU and very much less memory, because it has a WIFF reader built in.  One can then run reports on the generated file that give similar metrics in about another 30 seconds.

Unfortunately, we need to put some effort into improving the WIFF file reading before this tool is of use in production in Stoller.

**Comment by PaulBrack** [comment]
1) A number of key SwaMe metrics cannot be generated using Skyline. Of key importance, the lack of MS2 TIC metrics from Skyline are a deal-breaker.
2) Based on some more detailed use case discussion with Richard and Ivona, our use case at Stoller means that QC assessment within a few hours is good enough for now - both are happy with this to be within a few hours of the last run and don't see near-real-time as a critical need.
3) On initial testing, we should be able to turn around a conversion / QC assessment faster than 30m using some amended presets.

**Comment by Ozzard** [comment]
Down to 10 minutes by various means, including by using an old Mono version on the WIFF converter.  Closing - thanks!
