### ISSUE TITLE
Either put a hint in the docs for the cache-to-disk option that it caches in the temp directory, or allow the user to specify the path

### ISSUE THREAD

**Issue by Ozzard** [PaulBrack/Yamato#148]
I've learned from Paul that the cache goes to the temp directory.  It'd be good to document that in something the user sees in --help - either by documenting it, or by giving them an explicit option to set a path.

**Comment by PaulBrack** [comment]
Fixed.

@Ozzard please close if you're happy

https://github.com/PaulBrack/Yamato/commit/434e35919fc57f1882b86efbde9fb19e45d1d5b4

**Comment by Ozzard** [comment]
Looks good - closing.
