### ISSUE TITLE
When caching to disk, two jobs running on the same node should not use the same namespace for temporary files

### ISSUE THREAD

**Issue by Ozzard** [PaulBrack/Yamato#149]
At present, all jobs that cache to disk use files in the temp directory numbered by scan ID.  Two jobs running on the same node are highly likely to overwrite each others' files, leading to erroneous (but almost certainly sensible-looking) results.

**Comment by PaulBrack** [comment]
Fixed in https://github.com/PaulBrack/Yamato/commit/d5489a3979cc44b994c824aa2aa6fdb750188615

Please close if happy

**Comment by Ozzard** [comment]
I suggest deleting the directory on normal exit?

**Comment by PaulBrack** [comment]
Delete dir in https://github.com/PaulBrack/Yamato/commit/c33c7eaa674c1b3d9dcb4a7f9ff19bf14a7b58a5

Closing issue
