### ISSUE TITLE
Interquartile range is usually underestimated by InterQuartileRangeCalculator

### ISSUE THREAD

**Issue by Ozzard** [PaulBrack/Yamato#167]
Q3 is calculated as list[length / 4 * 3], and it should be list[length * 3 / 4].  This relates to order of calculation and truncation to integer.

Consider a list of length 7.
length * 3 / 4 is (7 * 3) / 4 = 21 / 4 = 5.
length / 4 * 3 is (7 / 4) * 3 = 1 * 3 = 3, which is the index of the median in this case, not the upper quartile.

We should check for similar integer-divide-then-multiply uses elsewhere in the codebase.

**Comment by marinaPauw** [comment]
Wow thanks for picking this up!

**Comment by Ozzard** [comment]
Fixed.
