### ISSUE TITLE
Path containing white space not accounted for

### ISSUE THREAD

**Issue by marinaPauw** [PaulBrack/Yamato#28]
If a folder name/file name in the path has white space, the white space is read as an exit code and the path becomes "D:\Analyst" instead of "D\Analyst data\....". Tried adding extra "" around the path in options and tried adding @ before "path", to no avail.

**Comment by PaulBrack** [comment]
Is this just a Windows but or a Linux bug too?

**Comment by marinaPauw** [comment]
Only tested on windows, let me try and test on Linux and get back to you.


Kind regards,
Marina Pauw

**Comment by marinaPauw** [comment]
This issue is specific to the launchsettings.json file by which the program is launched in debug mode. When the program is published and run via commandline this issue no longer exists.
