### ISSUE TITLE
Before I port Crawdad to C#, are we *certain* we're taking the right approach?

### ISSUE THREAD

**Issue by Ozzard** [PaulBrack/Yamato#43]
Pinging @PaulBrack technically, @marinaPauw for method.

Crawdad looks small enough to convert into C#, which would get us back to a pure .Net application.  I can do this, but I want to check that the approach we're taking is sane.  The code in CrawdadWrapper sets a *chromatogram*, i.e. a time vs. intensity plot, but the problem @PaulBrack described to me is peak-picking in the *mass* domain, i.e. a m/z vs. intensity plot.

Did Paul describe a different problem to me?  If we're using Crawdad to peak-pick by m/z, are we comfortable that it is the correct tool for the job?  I'd just like to confirm that before I put significant effort into porting!

**Comment by marinaPauw** [comment]
No, you are correct, Crawdad is called in the class
chromatogramMetricGenerator and is used for finding peaks in the RT vs
intensity plots, it does not do peak-picking in the m/z axis.

Kind regards,
Marina Pauw
