### ISSUE TITLE
Sciex Converter deletes the binary array if scan is missing, which causes SwaMe to crash

### ISSUE THREAD

**Issue by marinaPauw** [PaulBrack/Yamato#45]
We have dealt with missing scans from msconvert, but Sciex converter deals with them in a different manner, by leaving out the <binary><\binary> attribute completely.

**Comment by PaulBrack** [comment]
Marina, I think this is a duplicate of #81, can you confirm if fixed?

**Comment by marinaPauw** [comment]
Fixed
