### ISSUE TITLE
A file called "c:\temp\nlog-internal.log" is always created

### ISSUE THREAD

**Issue by mwalzer** [PaulBrack/Yamato#82]
with the standalone dotnet version, tested on linux. Might be a hint at hardcoded parameters?
I'd suggest something like`public static string GetTempFileName ();` or `public static string GetTempPath ();`

**Comment by PaulBrack** [comment]
This is hardcoded in nlog's config - applied fix on commit efaaad894be0422c24dcd25cac19a565fa3c515d

**Comment by PaulBrack** [comment]
Happy to let the internal log file fall into the executable folder so closing

**Comment by Ozzard** [comment]
Can I suggest using ${tempdir}/nlog-internal.log, per https://github.com/NLog/NLog/wiki/Internal-Logging ?  File creation in an application's directory has been a MUST NOT since Windows 2000, as applications installed in Program Files will not have write access to their installation directories.

**Comment by PaulBrack** [comment]
Didn't think about this going into Program Files as we're building it as standalone,, happy to put somewhere else

**Comment by PaulBrack** [comment]
As we're moving the log file outside Yamato, I've changed this to ${tempdir}/Yamato_nlog-internal.log so people know where it's coming from
